// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskModel(arg1) {
  return window['go']['main']['App']['AskModel'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function QueryContext(arg1) {
  return window['go']['main']['App']['QueryContext'](arg1);
}

export function StoreContext(arg1, arg2) {
  return window['go']['main']['App']['StoreContext'](arg1, arg2);
}
